### ISSUE TITLE
Forzar a XTTS a funcionar con CPU y no CUDA

### ISSUE THREAD

**Issue by KillyTheNetTerminal** [futurediffusion/Waifu-texto-ollama-xtts#1]
Current script directory: E:\waifu\Waifu-texto-ollama-xtts\
E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
TTS is not installed.
2024-06-21 19:38:51.618 | WARNING  | xtts_api_server.server:<module>:63 - 'Streaming Mode' has certain limitations, you can read about them here https://github.com/daswer123/xtts-api-server#about-streaming-mode
2024-06-21 19:38:51.619 | INFO     | xtts_api_server.RealtimeTTS.engines.coqui_engine:__init__:103 - Loading official model 'v2.0.2' for streaming
v2.0.2
E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
[2024-06-21 19:39:15,039] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-06-21 19:39:15,241] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
[2024-06-21 19:39:15,412] [INFO] [logging.py:96:log_dist] [Rank -1] DeepSpeed info: version=0.11.2+unknown, git-hash=unknown, git-branch=unknown
[2024-06-21 19:39:15,413] [WARNING] [config_utils.py:69:_process_deprecated_field] Config parameter replace_method is deprecated. This parameter is no longer needed, please remove from your call to DeepSpeed-inference
[2024-06-21 19:39:15,413] [WARNING] [config_utils.py:69:_process_deprecated_field] Config parameter mp_size is deprecated use tensor_parallel.tp_size instead
[2024-06-21 19:39:15,413] [INFO] [logging.py:96:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
[2024-06-21 19:39:15,607] [INFO] [logging.py:96:log_dist] [Rank -1] DeepSpeed-Inference config: {'layer_id': 0, 'hidden_size': 1024, 'intermediate_size': 4096, 'heads': 16, 'num_hidden_layers': -1, 'dtype': torch.float32, 'pre_layer_norm': True, 'norm_type': <NormType.LayerNorm: 1>, 'local_rank': -1, 'stochastic_mode': False, 'epsilon': 1e-05, 'mp_size': 1, 'scale_attention': True, 'triangular_masking': True, 'local_attention': False, 'window_size': 1, 'rotary_dim': -1, 'rotate_half': False, 'rotate_every_two': True, 'return_tuple': True, 'mlp_after_attn': True, 'mlp_act_func_type': <ActivationFuncType.GELU: 1>, 'specialized_mode': False, 'training_mp_size': 1, 'bigscience_bloom': False, 'max_out_tokens': 1024, 'min_out_tokens': 1, 'scale_attn_by_inverse_layer_idx': False, 'enable_qkv_quantization': False, 'use_mup': False, 'return_single_tuple': False, 'set_empty_params': False, 'transposed_mode': False, 'use_triton': False, 'triton_autotune': False, 'num_kv': -1, 'rope_theta': 10000}
CoquiEngine: Error initializing main coqui engine model: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Traceback (most recent call last):
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\xtts_api_server\RealtimeTTS\engines\coqui_engine.py", line 289, in _synthesize_worker
    tts.load_checkpoint(
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\TTS\tts\models\xtts.py", line 790, in load_checkpoint
    self.gpt.init_gpt_for_inference(kv_cache=self.args.kv_cache, use_deepspeed=use_deepspeed)
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\TTS\tts\layers\xtts\gpt.py", line 223, in init_gpt_for_inference
    self.ds_engine = deepspeed.init_inference(
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\__init__.py", line 342, in init_inference
    engine = InferenceEngine(model, config=ds_inference_config)
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\inference\engine.py", line 160, in __init__
    self._apply_injection_policy(config)
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\inference\engine.py", line 411, in _apply_injection_policy
    replace_transformer_layer(client_module, self.module, checkpoint, config, self.config)
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\module_inject\replace_module.py", line 339, in replace_transformer_layer
    replaced_module = replace_module(model=model,
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\module_inject\replace_module.py", line 583, in replace_module
    replaced_module, _ = _replace_module(model, policy, state_dict=sd)
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\module_inject\replace_module.py", line 643, in _replace_module
    _, layer_id = _replace_module(child,
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\module_inject\replace_module.py", line 643, in _replace_module
    _, layer_id = _replace_module(child,
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\module_inject\replace_module.py", line 619, in _replace_module
    replaced_module = policies[child.__class__][0](child,
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\module_inject\replace_module.py", line 298, in replace_fn
    new_module = replace_with_policy(child,
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\module_inject\replace_module.py", line 247, in replace_with_policy
    _container.create_module()
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\module_inject\containers\gpt2.py", line 20, in create_module
    self.module = DeepSpeedGPTInference(_config, mp_group=self.mp_group)
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\model_implementations\transformers\ds_gpt.py", line 20, in __init__
    super().__init__(config, mp_group, quantize_scales, quantize_groups, merge_count, mlp_extra_grouping)
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\model_implementations\transformers\ds_transformer.py", line 72, in __init__
    self.attention = DeepSpeedSelfAttention(self.config, mp_group, quantize_scales, quantize_groups,
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\ops\transformer\inference\ds_attention.py", line 27, in __init__
    device = get_accelerator().current_device_name()  #if config.bigscience_bloom else 'cpu'
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\accelerator\cuda_accelerator.py", line 61, in current_device_name
    return 'cuda:{}'.format(torch.cuda.current_device())
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\WarMa\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\WarMa\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\xtts_api_server\RealtimeTTS\engines\coqui_engine.py", line 289, in _synthesize_worker
    tts.load_checkpoint(
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\TTS\tts\models\xtts.py", line 790, in load_checkpoint
    self.gpt.init_gpt_for_inference(kv_cache=self.args.kv_cache, use_deepspeed=use_deepspeed)
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\TTS\tts\layers\xtts\gpt.py", line 223, in init_gpt_for_inference
    self.ds_engine = deepspeed.init_inference(
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\__init__.py", line 342, in init_inference
    engine = InferenceEngine(model, config=ds_inference_config)
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\inference\engine.py", line 160, in __init__
    self._apply_injection_policy(config)
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\inference\engine.py", line 411, in _apply_injection_policy
    replace_transformer_layer(client_module, self.module, checkpoint, config, self.config)
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\module_inject\replace_module.py", line 339, in replace_transformer_layer
    replaced_module = replace_module(model=model,
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\module_inject\replace_module.py", line 583, in replace_module
    replaced_module, _ = _replace_module(model, policy, state_dict=sd)
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\module_inject\replace_module.py", line 643, in _replace_module
    _, layer_id = _replace_module(child,
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\module_inject\replace_module.py", line 643, in _replace_module
    _, layer_id = _replace_module(child,
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\module_inject\replace_module.py", line 619, in _replace_module
    replaced_module = policies[child.__class__][0](child,
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\module_inject\replace_module.py", line 298, in replace_fn
    new_module = replace_with_policy(child,
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\module_inject\replace_module.py", line 247, in replace_with_policy
    _container.create_module()
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\module_inject\containers\gpt2.py", line 20, in create_module
    self.module = DeepSpeedGPTInference(_config, mp_group=self.mp_group)
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\model_implementations\transformers\ds_gpt.py", line 20, in __init__
    super().__init__(config, mp_group, quantize_scales, quantize_groups, merge_count, mlp_extra_grouping)
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\model_implementations\transformers\ds_transformer.py", line 72, in __init__
    self.attention = DeepSpeedSelfAttention(self.config, mp_group, quantize_scales, quantize_groups,
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\ops\transformer\inference\ds_attention.py", line 27, in __init__
    device = get_accelerator().current_device_name()  #if config.bigscience_bloom else 'cpu'
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\deepspeed\accelerator\cuda_accelerator.py", line 61, in current_device_name
    return 'cuda:{}'.format(torch.cuda.current_device())
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "E:\waifu\Waifu-texto-ollama-xtts\xtts-venv\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by KillyTheNetTerminal** [comment]
existe algun argumento para forzar el uso del CPU? ya que no cuento con una GPU Nvidea ;(
